name: Notify Telegram

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          curl -fSs -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            --data-urlencode "text=${{ inputs.message }}" \
            -d "parse_mode=MarkdownV2" \
            -d "disable_web_page_preview=true"
